### ISSUE TITLE
File are up/downloaded relative to the gem

### ISSUE THREAD

**Issue by mattisfrommars** [chinoio/chino-ruby#4]
when specifying a path to upload/download blobs they will be located relative to the gem rather than the application requiring it. (At least I think so, based on what I saw from the tests, I haven't yet used it in a real app yet)

**Comment by aarighi** [comment]
This repository has been migrated to https://gitlab.com/chinoio-public/sdk-chino-ruby and will no longer be maintained on GitHub. Please reach out to tech-support@chino.io for any question, or if you wish to contribute to the SDK development.
